---
- name: Install K3s on openSUSE MicroOS
  hosts: rancher_node
  roles:
    - role: k3s_install
  # We are running everything as root
  # become: yes
  vars:
    necessary_packages: k3s-install helm

  tasks:
    - name: Add Jetstack Helm repository for cert-manager
      ansible.builtin.shell: |
        helm repo add jetstack https://charts.jetstack.io
        helm repo update

    - name: Install cert-manager via Helm
      ansible.builtin.shell: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/{{cert_manager_version}}/cert-manager.crds.yaml
        helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    - name: Add Rancher Helm repository
      ansible.builtin.shell: |
        helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
        helm repo update

    - name: Install Rancher via Helm
      ansible.builtin.shell: |
        helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace \
        --set hostname={{ rancher_hostname }} \
        --set replicas=1 \
        --set bootstrapPassword={{ rancher_bootstrap_password }}
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    - name: Copy kubeconfig from the K3s node to local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: kubeconfig-remote.yaml
        flat: yes
        validate_checksum: no
      become: yes

    - name: Update server address in kubeconfig for local access
      delegate_to: localhost
      ansible.builtin.replace:
        path: kubeconfig-remote.yaml
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://{{ hostvars[inventory_hostname].ansible_host }}:6443'


